FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
MAINTAINER RODRIGO HASSE
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS sdk
WORKDIR /src
COPY ["API_2/API/API.csproj", "API_2/API/"]
COPY ["API_2/Core/Core.csproj", "API_2/Core/"]
COPY ["API_2/Application/Application.csproj", "API_2/Application/"]
COPY ["API_2/CamadaCross/Cross.csproj", "API_2/CamadaCross/"]

RUN dotnet restore "API_2/API/API.csproj"
COPY . .
WORKDIR "/src/API_2/API"
RUN dotnet build "API.csproj" -c Release -o /app/build
FROM sdk AS publish
RUN dotnet publish "API.csproj" -c Release -o /app/publish
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "API.dll"]